sudo: required

services:
  - docker


env:
  - DOCKER_TAG=latest

before_script:
  - docker run -d -p 5433:5432 --name postgres postgres

script:
  - sudo ss -lntp
  - sudo docker ps

after_success:
  - echo "Test complete"
