sudo: required

services:
  - docker


env:
  - DOCKER_TAG=latest

before_script:
  - docker run -d -p 5433:5432 --name postgres postgres
  - docker run -d --name ubuntu ubuntu bash -c "sleep 60"

env:
  - HOST=$(/sbin/ip route|awk '/default/ { print $3 }')
  - CONTAINER=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres)

script:
  - sudo ss -lntp
  - sudo iptables -L
  - sudo iptables-save
  - sudo docker ps
#  - docker exec ubuntu bash -c "apt-get -y update && apt -y install curl && curl -v $HOST:5433"
  - docker exec ubuntu bash -c "apt-get -y update && apt -y install curl && curl -v $CONTAINER:5433"
  - docker exec ubuntu bash -c "curl -v $CONTAINER:5432"

after_success:
  - echo "Test complete"
