sudo: required

services:
  - docker


env:
  - DOCKER_TAG=latest

before_script:
  - docker run -d -p 5433:5432 --name postgres postgres
  - docker run -d --name ubuntu ubuntu bash -c "sleep 60"

env:
  - HOST=$(/sbin/ip route|awk '/default/ { print $3 }')

script:
  - sudo ss -lntp
  - sudo docker ps
  - docker exec ubuntu curl -v $HOST:5433

after_success:
  - echo "Test complete"
